language: ruby
rvm:
- 2.3.3
addons:
  postgresql: '9.4'
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
before_install:
- openssl aes-256-cbc -K $encrypted_8db9eb37f9bb_key -iv $encrypted_8db9eb37f9bb_iv
  -in secrets.yml.enc -out config/secrets.yml -d